In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("breast_cancer_enhanced_dataset.csv")

In [3]:
print(df.head())

             id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0  5.683796e+06         B    11.829858     21.726166       75.154378
1 -6.253379e+06         B    10.991150     17.103260       71.798929
2  4.213892e+06         M    21.433519     15.092437      142.753006
3 -2.986069e+06         B    11.700452     14.872127       74.154481
4  6.469594e+05         B    13.259377     17.212990       83.621014

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0   435.022394         0.087089          0.050717        0.015868
1   381.386295         0.089339          0.109498        0.097344
2  1392.399890         0.099557          0.152079        0.193372
3   404.112556         0.101291          0.077563        0.043749
4   521.124238         0.072905          0.043312        0.046983

   concave points_mean  shape_irregularity  border_complexity  \
0             0.011641            0.078226           0.000185
1             0.035629            0.242470           0.003468
2             0.126922            0.472373           0.024543
3             0.028747            0.150059           0.001258
4             0.010096            0.100391           0.000474

   tumor_aggressiveness  radius_texture_interaction  \
0              0.026075                  257.017451
1              0.080823                  187.984489
2              0.157458                  323.484034
3              0.050020                  174.010599
4              0.033464                  228.233523

   radius_concavity_interaction  concavity_density  malignancy_risk_score
0                      0.187718           0.000036              22.433798
1                      1.069921           0.000255              24.021839
2                      4.144647           0.000139              49.053992
3                      0.511885           0.000108              23.276145
4                      0.622960           0.000090              25.647074

In [4]:
df['concavity_density']

0       0.000036
1       0.000255
2       0.000139
3       0.000108
4       0.000090
          ...
5495    0.000162
5496    0.000021
5497    0.000145
5498    0.000236
5499    0.000115
Name: concavity_density, Length: 5500, dtype: float64

In [5]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
count,5.500000e+03,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000
mean,2.705450e+07,14.095290,19.317068,91.749574,651.332914,0.096027,0.103069,0.086652,0.048172,0.237894,0.006983,0.079298,276.771030,1.408473,0.000129,29.831833
std,1.135108e+08,3.484868,4.350629,24.012506,346.027394,0.013878,0.052939,0.078752,0.038531,0.164068,0.011284,0.054689,107.515404,1.605029,0.000117,9.282654
min,-1.637568e+07,6.817646,9.522736,42.639188,123.928240,0.052200,0.015551,-0.006232,-0.002668,0.017291,-0.000020,0.005764,92.849788,-0.064863,-0.000023,12.370635
25%,-4.464305e+05,11.679531,16.196326,75.119335,420.093960,0.085863,0.063526,0.028775,0.019967,0.113784,0.000600,0.037928,199.843614,0.342645,0.000061,23.293325
50%,2.982231e+06,13.339209,18.817023,86.222090,549.472961,0.095362,0.090793,0.058934,0.032845,0.190299,0.001889,0.063433,246.009655,0.745327,0.000107,26.953460
75%,8.362453e+06,15.760529,21.841027,103.688058,776.638240,0.105008,0.129659,0.125716,0.072017,0.327721,0.008902,0.109240,338.834746,1.992114,0.000169,35.026766
max,9.235889e+08,28.341004,39.442971,188.983008,2507.982355,0.164055,0.348835,0.429627,0.202662,0.919553,0.086579,0.306518,725.185848,10.439435,0.001431,67.030216

In [6]:
df=df.drop('id',axis=1)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
0,B,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,0.000185,0.026075,257.017451,0.187718,0.000036,22.433798
1,B,10.991150,17.103260,71.798929,381.386295,0.089339,0.109498,0.097344,0.035629,0.242470,0.003468,0.080823,187.984489,1.069921,0.000255,24.021839
2,M,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992
3,B,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747,0.150059,0.001258,0.050020,174.010599,0.511885,0.000108,23.276145
4,B,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074

In [8]:
df['diagnosis']=df['diagnosis'].map({"B":0,"M":1})

In [9]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
0,0,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,0.000185,0.026075,257.017451,0.187718,0.000036,22.433798
1,0,10.991150,17.103260,71.798929,381.386295,0.089339,0.109498,0.097344,0.035629,0.242470,0.003468,0.080823,187.984489,1.069921,0.000255,24.021839
2,1,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992
3,0,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747,0.150059,0.001258,0.050020,174.010599,0.511885,0.000108,23.276145
4,0,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.33,random_state=42)

In [12]:
from sklearn.preprocessing import MinMaxScaler
mx=MinMaxScaler()
x_train = mx.fit_transform(x_train)
x_test = mx.transform(x_test)

In [13]:
x_train

array([[0.39809091, 0.24408415, 0.41571837, ..., 0.36645091, 0.25319135,
        0.48544477],
       [0.33974812, 0.24513936, 0.3196567 , ..., 0.04171346, 0.04468498,
        0.27316038],
       [0.31752991, 0.44714345, 0.30244566, ..., 0.04396849, 0.05043113,
        0.25728072],
       ...,
       [0.44996363, 0.35077474, 0.45516577, ..., 0.28995392, 0.16561379,
        0.47072247],
       [0.00482336, 0.12297389, 0.00789171, ..., 0.00547968, 0.01084967,
        0.00403558],
       [0.19091098, 0.39506059, 0.18110124, ..., 0.00442666, 0.01220393,
        0.13854039]], shape=(3685, 15))

In [14]:
from sklearn.ensemble import RandomForestClassifier
rnd = RandomForestClassifier(n_estimators=100,random_state=42)
rnd.fit(x_train,y_train)
y_pred = rnd.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.9972451790633609
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1182
           1       0.99      1.00      1.00       633

    accuracy                           1.00      1815
   macro avg       1.00      1.00      1.00      1815
weighted avg       1.00      1.00      1.00      1815

In [17]:
# Train data ki accuracy
train_pred = rnd.predict(x_train)
train_acc = accuracy_score(y_train, train_pred)

# Test data ki accuracy
test_pred = rnd.predict(x_test)
test_acc = accuracy_score(y_test, test_pred)

print(f"Training Accuracy: {train_acc * 100:.2f}%")
print(f"Testing Accuracy: {test_acc * 100:.2f}%")

Training Accuracy: 100.00%
Testing Accuracy: 99.72%

In [61]:
import joblib

# Apne trained random forest model ko save karein
joblib.dump(rnd, 'random_forest_model.joblib')
print("Model locally save ho gaya hai!")

Model locally save ho gaya hai!